/* Brand positioning refresh — games first, digital products second. */
(() => {
  const D = window.FEATHER_TRANSLATIONS ||= {};
  const shared = {
    fr: { navRoadmap: "Accueil", navProject: "Prochain jeu", navTeam: "Le studio", navGenable: "Genable AI" },
    en: { navRoadmap: "Home", navProject: "Next game", navTeam: "Studio", navGenable: "Genable AI" },
    es: { navRoadmap: "Inicio", navProject: "Próximo juego", navTeam: "Estudio", navGenable: "Genable AI" },
    it: { navRoadmap: "Home", navProject: "Prossimo gioco", navTeam: "Studio", navGenable: "Genable AI" },
    de: { navRoadmap: "Start", navProject: "Nächstes Spiel", navTeam: "Studio", navGenable: "Genable AI" },
    zh: { navRoadmap: "首页", navProject: "下一款游戏", navTeam: "工作室", navGenable: "Genable AI" },
    ja: { navRoadmap: "ホーム", navProject: "次回作", navTeam: "スタジオ", navGenable: "Genable AI" },
    ko: { navRoadmap: "홈", navProject: "다음 게임", navTeam: "스튜디오", navGenable: "Genable AI" }
  };
  Object.entries(shared).forEach(([lang, values]) => Object.assign(D[lang] ||= {}, values));
  if (D.fr) D.fr.statusValue = "En finalisation";
  if (D.en) D.en.statusValue = "In finalization";

  D.fr.home = {
    title: "KageCrest Studio — Studio de jeux indépendant",
    description: "Studio indépendant dédié avant tout aux jeux vidéo, avec un pôle secondaire de produits numériques.",
    navHome: "Accueil", navGames: "Jeux", navProducts: "Produits", navRoadmap: "Roadmap",
    kicker: "Studio indépendant · Jeux vidéo avant tout",
    heroTitle: "Nous créons des jeux qui ont leur propre voix.",
    heroCopy: "KageCrest Studio imagine et développe principalement des jeux vidéo indépendants. En parallèle, notre savoir-faire technique donne naissance à une sélection de produits numériques utiles.",
    discoverGame: "Découvrir Pipi Panic", followStudio: "Suivre le studio",
    storeNote: "La page Google Play sera ajoutée dès la validation de la version de production.", primaryActivity: "Activité principale · Jeux vidéo",
    gamesKicker: "Notre cœur de métier", gamesTitle: "Des jeux indépendants, conçus avec caractère.", gamesIntro: "De l’idée au lancement, nous construisons nos univers, leur gameplay et leur identité avec une production volontairement agile.",
    currentGame: "Jeu en finalisation", pipiIntro: "Un jeu mobile cartoon, direct et volontairement absurde, où chaque urgence devient une situation de chaos.", independentProduction: "Production indépendante", explorePipi: "Explorer le jeu",
    nextGameLabel: "Après Pipi Panic", nextGameTitle: "Une nouvelle création est déjà en préparation.",
    productsKicker: "Activité secondaire", productsTitle: "Notre expertise sert aussi des produits numériques.", productsIntro: "Cette activité annexe transforme nos compétences en développement, automatisation et interface en outils destinés aux professionnels — sans détourner le studio de sa vocation première : créer des jeux.",
    productDevelopment: "Produit en développement", genableIntro: "Un CRM intelligent et configurable pour centraliser contacts, devis, factures, projets et automatisations.", tryDemo: "Tester la démo", learnMore: "En savoir plus →",
    roadmapKicker: "Feuille de route publique", roadmapTitle: "Ce qui avance actuellement.", roadmapIntro: "Une vue volontairement concise des productions annoncées. Les projets confidentiels restent confidentiels jusqu’au bon moment.", finalization: "Finalisation", preproduction: "Préproduction", secondaryProduct: "Pôle produits", nextCreation: "Nouvelle création", pipiRoadmap: "Polissage, publication mobile et préparation du lancement.", nextRoadmap: "Un prochain jeu prend forme avant sa révélation officielle.", genableRoadmap: "Consolidation du CRM et préparation des premiers cas clients.",
    ctaKicker: "Suivre l’aventure", ctaTitle: "Découvrez les créateurs derrière le studio.", ctaCopy: "Retrouvez nos chaînes, nos coulisses et les moyens de nous contacter. Le Discord officiel du studio arrivera plus tard.", meetTeam: "Découvrir l’équipe", contact: "Nous contacter", team: "L’équipe", privacy: "Confidentialité", terms: "Conditions"
  };

  D.en.home = {
    title: "KageCrest Studio — Independent game studio", description: "An independent studio focused primarily on video games, with a secondary digital products division.",
    navHome: "Home", navGames: "Games", navProducts: "Products", navRoadmap: "Roadmap", kicker: "Independent studio · Games first", heroTitle: "We create games with a voice of their own.", heroCopy: "KageCrest Studio primarily creates independent video games. Alongside them, our technical expertise powers a focused selection of useful digital products.", discoverGame: "Discover Pipi Panic", followStudio: "Follow the studio", storeNote: "The Google Play page will be added as soon as the production release is approved.", primaryActivity: "Primary activity · Video games", gamesKicker: "Our core activity", gamesTitle: "Independent games built with character.", gamesIntro: "From idea to launch, we craft our worlds, gameplay and identity through an intentionally agile production process.", currentGame: "Game in finalization", pipiIntro: "A direct, cartoon mobile game where every urgent situation turns into chaos.", independentProduction: "Independent production", explorePipi: "Explore the game", nextGameLabel: "After Pipi Panic", nextGameTitle: "A new creation is already taking shape.", productsKicker: "Secondary activity", productsTitle: "Our expertise also powers digital products.", productsIntro: "This complementary activity turns our development, automation and interface skills into professional tools — without changing our primary purpose: making games.", productDevelopment: "Product in development", genableIntro: "An intelligent, configurable CRM for contacts, quotes, invoices, projects and automations.", tryDemo: "Try the demo", learnMore: "Learn more →", roadmapKicker: "Public roadmap", roadmapTitle: "What we are working on.", roadmapIntro: "A concise view of announced productions. Confidential projects stay confidential until the right moment.", finalization: "Finalization", preproduction: "Pre-production", secondaryProduct: "Products division", nextCreation: "New creation", pipiRoadmap: "Polish, mobile publishing and launch preparation.", nextRoadmap: "Our next game is taking shape ahead of its official reveal.", genableRoadmap: "CRM consolidation and preparation of initial customer cases.", ctaKicker: "Follow the journey", ctaTitle: "Meet the creators behind the studio.", ctaCopy: "Find our channels, behind-the-scenes updates and contact details. The studio’s official Discord will come later.", meetTeam: "Meet the team", contact: "Contact us", team: "Team", privacy: "Privacy", terms: "Terms"
  };

  const localizedHomes = {
    es: {
      title:"KageCrest Studio — Estudio independiente de videojuegos",description:"Estudio independiente centrado principalmente en videojuegos, con una actividad secundaria de productos digitales.",navHome:"Inicio",navGames:"Juegos",navProducts:"Productos",navRoadmap:"Roadmap",kicker:"Estudio independiente · Videojuegos ante todo",heroTitle:"Creamos juegos con voz propia.",heroCopy:"KageCrest Studio imagina y desarrolla principalmente videojuegos independientes. En paralelo, nuestra experiencia técnica da vida a una selección de productos digitales útiles.",discoverGame:"Descubrir Pipi Panic",followStudio:"Seguir el estudio",storeNote:"La página de Google Play se añadirá cuando se apruebe la versión de producción.",primaryActivity:"Actividad principal · Videojuegos",gamesKicker:"Nuestra actividad principal",gamesTitle:"Juegos independientes creados con carácter.",gamesIntro:"De la idea al lanzamiento, construimos nuestros universos, su jugabilidad y su identidad con una producción deliberadamente ágil.",currentGame:"Juego en fase final",pipiIntro:"Un juego móvil cartoon, directo y deliberadamente absurdo, donde cada urgencia se convierte en caos.",independentProduction:"Producción independiente",explorePipi:"Explorar el juego",nextGameLabel:"Después de Pipi Panic",nextGameTitle:"Una nueva creación ya está en preparación.",productsKicker:"Actividad secundaria",productsTitle:"Nuestra experiencia también impulsa productos digitales.",productsIntro:"Esta actividad complementaria convierte nuestras competencias en desarrollo, automatización e interfaces en herramientas profesionales, sin apartar al estudio de su vocación principal: crear juegos.",productDevelopment:"Producto en desarrollo",genableIntro:"Un CRM inteligente y configurable para centralizar contactos, presupuestos, facturas, proyectos y automatizaciones.",tryDemo:"Probar la demo",learnMore:"Más información →",roadmapKicker:"Roadmap público",roadmapTitle:"En qué estamos trabajando.",roadmapIntro:"Una visión concisa de las producciones anunciadas. Los proyectos confidenciales siguen siéndolo hasta el momento adecuado.",finalization:"Fase final",preproduction:"Preproducción",secondaryProduct:"Área de productos",nextCreation:"Nueva creación",pipiRoadmap:"Pulido, publicación móvil y preparación del lanzamiento.",nextRoadmap:"Nuestro próximo juego toma forma antes de su presentación oficial.",genableRoadmap:"Consolidación del CRM y preparación de los primeros casos de clientes.",ctaKicker:"Seguir la aventura",ctaTitle:"Conoce a los creadores del estudio.",ctaCopy:"Encuentra nuestros canales, contenidos entre bastidores y formas de contacto. El Discord oficial del estudio llegará más adelante.",meetTeam:"Conocer al equipo",contact:"Contactarnos",team:"El equipo",privacy:"Privacidad",terms:"Condiciones"
    },
    it: {
      title:"KageCrest Studio — Studio indipendente di videogiochi",description:"Studio indipendente dedicato soprattutto ai videogiochi, con un'attività secondaria di prodotti digitali.",navHome:"Home",navGames:"Giochi",navProducts:"Prodotti",navRoadmap:"Roadmap",kicker:"Studio indipendente · Prima di tutto videogiochi",heroTitle:"Creiamo giochi con una voce propria.",heroCopy:"KageCrest Studio immagina e sviluppa principalmente videogiochi indipendenti. Parallelamente, la nostra esperienza tecnica dà vita a una selezione di prodotti digitali utili.",discoverGame:"Scopri Pipi Panic",followStudio:"Segui lo studio",storeNote:"La pagina Google Play sarà aggiunta non appena la versione di produzione sarà approvata.",primaryActivity:"Attività principale · Videogiochi",gamesKicker:"La nostra attività principale",gamesTitle:"Giochi indipendenti creati con carattere.",gamesIntro:"Dall'idea al lancio, costruiamo universi, gameplay e identità con una produzione volutamente agile.",currentGame:"Gioco in fase finale",pipiIntro:"Un gioco mobile cartoon, diretto e volutamente assurdo, dove ogni urgenza diventa caos.",independentProduction:"Produzione indipendente",explorePipi:"Esplora il gioco",nextGameLabel:"Dopo Pipi Panic",nextGameTitle:"Una nuova creazione è già in preparazione.",productsKicker:"Attività secondaria",productsTitle:"La nostra esperienza alimenta anche prodotti digitali.",productsIntro:"Questa attività complementare trasforma le nostre competenze di sviluppo, automazione e interfaccia in strumenti professionali, senza allontanare lo studio dalla sua vocazione principale: creare giochi.",productDevelopment:"Prodotto in sviluppo",genableIntro:"Un CRM intelligente e configurabile per centralizzare contatti, preventivi, fatture, progetti e automazioni.",tryDemo:"Prova la demo",learnMore:"Scopri di più →",roadmapKicker:"Roadmap pubblica",roadmapTitle:"A cosa stiamo lavorando.",roadmapIntro:"Una panoramica concisa delle produzioni annunciate. I progetti riservati restano tali fino al momento giusto.",finalization:"Fase finale",preproduction:"Pre-produzione",secondaryProduct:"Area prodotti",nextCreation:"Nuova creazione",pipiRoadmap:"Rifinitura, pubblicazione mobile e preparazione del lancio.",nextRoadmap:"Il prossimo gioco prende forma prima della presentazione ufficiale.",genableRoadmap:"Consolidamento del CRM e preparazione dei primi casi cliente.",ctaKicker:"Segui l'avventura",ctaTitle:"Scopri i creatori dietro lo studio.",ctaCopy:"Trova i nostri canali, i retroscena e i contatti. Il Discord ufficiale dello studio arriverà più avanti.",meetTeam:"Scopri il team",contact:"Contattaci",team:"Il team",privacy:"Privacy",terms:"Condizioni"
    },
    de: {
      title:"KageCrest Studio — Unabhängiges Spielestudio",description:"Unabhängiges Studio mit Schwerpunkt Videospiele und einem ergänzenden Bereich für digitale Produkte.",navHome:"Start",navGames:"Spiele",navProducts:"Produkte",navRoadmap:"Roadmap",kicker:"Unabhängiges Studio · Spiele zuerst",heroTitle:"Wir entwickeln Spiele mit einer eigenen Stimme.",heroCopy:"KageCrest Studio entwickelt in erster Linie unabhängige Videospiele. Daneben entstehen aus unserer technischen Erfahrung ausgewählte nützliche Digitalprodukte.",discoverGame:"Pipi Panic entdecken",followStudio:"Studio folgen",storeNote:"Die Google-Play-Seite wird ergänzt, sobald die Produktionsversion freigegeben ist.",primaryActivity:"Haupttätigkeit · Videospiele",gamesKicker:"Unser Kerngeschäft",gamesTitle:"Unabhängige Spiele mit Charakter.",gamesIntro:"Von der Idee bis zur Veröffentlichung gestalten wir Welten, Gameplay und Identität in einem bewusst agilen Produktionsprozess.",currentGame:"Spiel in der Abschlussphase",pipiIntro:"Ein direktes, bewusst absurdes Cartoon-Mobile-Game, in dem jeder Notfall im Chaos endet.",independentProduction:"Unabhängige Produktion",explorePipi:"Spiel entdecken",nextGameLabel:"Nach Pipi Panic",nextGameTitle:"Eine neue Kreation ist bereits in Vorbereitung.",productsKicker:"Nebentätigkeit",productsTitle:"Unsere Erfahrung fließt auch in digitale Produkte.",productsIntro:"Dieser ergänzende Bereich verwandelt unsere Kompetenzen in Entwicklung, Automatisierung und Interface-Design in professionelle Werkzeuge, ohne den Hauptzweck des Studios zu verändern: Spiele zu entwickeln.",productDevelopment:"Produkt in Entwicklung",genableIntro:"Ein intelligentes, konfigurierbares CRM für Kontakte, Angebote, Rechnungen, Projekte und Automatisierungen.",tryDemo:"Demo testen",learnMore:"Mehr erfahren →",roadmapKicker:"Öffentliche Roadmap",roadmapTitle:"Woran wir gerade arbeiten.",roadmapIntro:"Ein kompakter Überblick über angekündigte Produktionen. Vertrauliche Projekte bleiben bis zum richtigen Zeitpunkt vertraulich.",finalization:"Abschlussphase",preproduction:"Vorproduktion",secondaryProduct:"Produktbereich",nextCreation:"Neue Kreation",pipiRoadmap:"Feinschliff, mobile Veröffentlichung und Startvorbereitung.",nextRoadmap:"Unser nächstes Spiel nimmt vor seiner offiziellen Enthüllung Gestalt an.",genableRoadmap:"CRM-Konsolidierung und Vorbereitung erster Kundenfälle.",ctaKicker:"Die Reise verfolgen",ctaTitle:"Lerne die Menschen hinter dem Studio kennen.",ctaCopy:"Entdecke unsere Kanäle, Einblicke hinter die Kulissen und Kontaktmöglichkeiten. Der offizielle Studio-Discord folgt später.",meetTeam:"Team kennenlernen",contact:"Kontakt",team:"Team",privacy:"Datenschutz",terms:"Bedingungen"
    },
    zh: {
      title:"KageCrest Studio — 独立游戏工作室",description:"以电子游戏为核心业务、数字产品为辅助业务的独立工作室。",navHome:"首页",navGames:"游戏",navProducts:"产品",navRoadmap:"路线图",kicker:"独立工作室 · 游戏优先",heroTitle:"我们创造拥有独特声音的游戏。",heroCopy:"KageCrest Studio 主要构思并开发独立电子游戏。同时，我们也运用技术经验打造一系列实用的数字产品。",discoverGame:"了解 Pipi Panic",followStudio:"关注工作室",storeNote:"制作版本通过审核后，我们将添加 Google Play 页面。",primaryActivity:"核心业务 · 电子游戏",gamesKicker:"我们的核心业务",gamesTitle:"打造富有个性的独立游戏。",gamesIntro:"从创意到发布，我们以灵活的制作方式构建游戏世界、玩法与独特身份。",currentGame:"游戏收尾阶段",pipiIntro:"一款直接、卡通且刻意荒诞的手机游戏，每次紧急情况都会演变成混乱。",independentProduction:"独立制作",explorePipi:"探索游戏",nextGameLabel:"Pipi Panic 之后",nextGameTitle:"一款全新作品已在筹备中。",productsKicker:"辅助业务",productsTitle:"我们的专业能力也用于数字产品。",productsIntro:"这项辅助业务把我们在开发、自动化和界面方面的能力转化为专业工具，同时不改变工作室的首要使命：制作游戏。",productDevelopment:"产品开发中",genableIntro:"一款可配置的智能 CRM，用于集中管理联系人、报价、发票、项目和自动化。",tryDemo:"体验演示",learnMore:"了解更多 →",roadmapKicker:"公开路线图",roadmapTitle:"我们目前正在推进的项目。",roadmapIntro:"简要展示已公布的作品。保密项目将在合适的时机才会公开。",finalization:"收尾阶段",preproduction:"前期制作",secondaryProduct:"产品部门",nextCreation:"全新作品",pipiRoadmap:"最终打磨、移动端发布和上线准备。",nextRoadmap:"下一款游戏正在正式公开前逐步成形。",genableRoadmap:"完善 CRM，并准备首批客户案例。",ctaKicker:"关注我们的旅程",ctaTitle:"认识工作室背后的创作者。",ctaCopy:"查看我们的频道、幕后内容和联系方式。工作室官方 Discord 将在之后推出。",meetTeam:"认识团队",contact:"联系我们",team:"团队",privacy:"隐私",terms:"条款"
    },
    ja: {
      title:"KageCrest Studio — インディーゲームスタジオ",description:"ゲームを主軸に、デジタル製品も手がけるインディーゲームスタジオです。",navHome:"ホーム",navGames:"ゲーム",navProducts:"製品",navRoadmap:"ロードマップ",kicker:"インディーゲームスタジオ · ゲームを第一に",heroTitle:"独自の声を持つゲームをつくる。",heroCopy:"KageCrest Studio は、主にインディーゲームを企画・開発しています。同時に、技術力を生かした実用的なデジタル製品も展開しています。",discoverGame:"Pipi Panicを見る",followStudio:"スタジオをフォロー",storeNote:"製品版の承認後、Google Play ページを追加します。",primaryActivity:"主な事業 · ビデオゲーム",gamesKicker:"私たちの中心事業",gamesTitle:"個性あるインディーゲームを。",gamesIntro:"アイデアからリリースまで、機動力のある制作体制で世界観、ゲームプレイ、個性を形にします。",currentGame:"最終調整中",pipiIntro:"緊急事態が次々と混乱に変わる、ストレートで意図的に突飛なカートゥーン調モバイルゲームです。",independentProduction:"インディー制作",explorePipi:"ゲームを見る",nextGameLabel:"Pipi Panic の次",nextGameTitle:"新たな作品がすでに動き始めています。",productsKicker:"副次事業",productsTitle:"技術力をデジタル製品にも。",productsIntro:"開発、自動化、インターフェースの技術を業務向けツールに生かす活動です。スタジオの第一の使命であるゲーム制作は変わりません。",productDevelopment:"製品開発中",genableIntro:"連絡先、見積書、請求書、プロジェクト、自動化を一元管理する設定可能なスマート CRM。",tryDemo:"デモを試す",learnMore:"詳しく見る →",roadmapKicker:"公開ロードマップ",roadmapTitle:"現在進行中のプロジェクト。",roadmapIntro:"発表済みの制作を簡潔に紹介します。非公開プロジェクトは適切な時期まで公開しません。",finalization:"最終調整",preproduction:"プリプロダクション",secondaryProduct:"製品部門",nextCreation:"新作",pipiRoadmap:"最終調整、モバイル公開、ローンチ準備。",nextRoadmap:"次回作は正式発表に向けて形になりつつあります。",genableRoadmap:"CRM の統合と初期顧客事例の準備。",ctaKicker:"活動をフォロー",ctaTitle:"スタジオを支えるクリエイターを紹介します。",ctaCopy:"公式チャンネル、制作の舞台裏、連絡先をご覧ください。スタジオ公式 Discord は今後開設予定です。",meetTeam:"チームを見る",contact:"お問い合わせ",team:"チーム",privacy:"プライバシー",terms:"利用規約"
    },
    ko: {
      title:"KageCrest Studio — 인디 게임 스튜디오",description:"비디오 게임을 주력으로 하고 디지털 제품을 부가적으로 개발하는 인디 스튜디오입니다.",navHome:"홈",navGames:"게임",navProducts:"제품",navRoadmap:"로드맵",kicker:"인디 스튜디오 · 게임을 최우선으로",heroTitle:"우리만의 목소리를 가진 게임을 만듭니다.",heroCopy:"KageCrest Studio는 주로 인디 비디오 게임을 기획하고 개발합니다. 동시에 기술력을 활용해 유용한 디지털 제품도 선별적으로 만듭니다.",discoverGame:"Pipi Panic 보기",followStudio:"스튜디오 팔로우",storeNote:"프로덕션 버전이 승인되면 Google Play 페이지를 추가할 예정입니다.",primaryActivity:"주요 활동 · 비디오 게임",gamesKicker:"핵심 사업",gamesTitle:"개성 있는 인디 게임을 만듭니다.",gamesIntro:"아이디어부터 출시까지, 민첩한 제작 방식으로 세계관과 게임플레이, 정체성을 완성합니다.",currentGame:"마무리 단계",pipiIntro:"모든 긴급 상황이 혼돈으로 변하는 직관적이고 의도적으로 황당한 카툰 모바일 게임입니다.",independentProduction:"인디 제작",explorePipi:"게임 살펴보기",nextGameLabel:"Pipi Panic 이후",nextGameTitle:"새로운 작품이 이미 준비되고 있습니다.",productsKicker:"부가 사업",productsTitle:"우리의 전문성은 디지털 제품에도 이어집니다.",productsIntro:"개발, 자동화, 인터페이스 역량을 전문 도구로 확장하는 부가 활동입니다. 스튜디오의 최우선 목표인 게임 제작은 변하지 않습니다.",productDevelopment:"제품 개발 중",genableIntro:"연락처, 견적, 청구서, 프로젝트와 자동화를 한곳에서 관리하는 설정 가능한 스마트 CRM입니다.",tryDemo:"데모 체험",learnMore:"자세히 보기 →",roadmapKicker:"공개 로드맵",roadmapTitle:"현재 진행 중인 작업.",roadmapIntro:"공개된 제작물을 간결하게 소개합니다. 비공개 프로젝트는 적절한 시점까지 공개하지 않습니다.",finalization:"마무리",preproduction:"프리프로덕션",secondaryProduct:"제품 부문",nextCreation:"새로운 작품",pipiRoadmap:"마무리 작업, 모바일 출시와 론칭 준비.",nextRoadmap:"다음 게임이 공식 공개를 앞두고 형태를 갖춰가고 있습니다.",genableRoadmap:"CRM 통합과 초기 고객 사례 준비.",ctaKicker:"여정 팔로우",ctaTitle:"스튜디오를 만드는 크리에이터를 만나보세요.",ctaCopy:"공식 채널, 제작 비하인드와 연락처를 확인하세요. 스튜디오 공식 Discord는 추후 개설됩니다.",meetTeam:"팀 소개",contact:"문의하기",team:"팀",privacy:"개인정보",terms:"이용약관"
    }
  };
  Object.entries(localizedHomes).forEach(([lang, values]) => { D[lang].home = values; });

  const pageRefresh = {
    fr:{aboutTitle:"Le studio — KageCrest Studio",heroTitle:"Le CRM intelligent, à installer seul ou avec accompagnement.",turnkey:"Installation flexible",processKicker:"Deux modes d’installation",processTitle:"Installez Genable AI vous-même ou confiez-nous sa mise en place.",step1Title:"Installation autonome",step1Copy:"Vous installez et configurez la solution avec la documentation fournie, sans frais d’installation supplémentaires.",step2Title:"Installation accompagnée",step2Copy:"Nous pouvons installer, configurer et préparer votre environnement. Cette prestation optionnelle est ajoutée au devis.",step3Title:"Configuration métier",step3Copy:"Les adaptations, imports de données, intégrations et automatisations spécifiques sont évalués séparément selon vos besoins."},
    en:{aboutTitle:"The studio — KageCrest Studio",heroTitle:"The intelligent CRM, self-installed or supported.",turnkey:"Flexible installation",processKicker:"Two installation options",processTitle:"Install Genable AI yourself or let us set it up for you.",step1Title:"Self-installation",step1Copy:"Install and configure the solution with the supplied documentation, with no additional installation fee.",step2Title:"Assisted installation",step2Copy:"We can install, configure and prepare your environment. This optional service is added to the quote.",step3Title:"Business configuration",step3Copy:"Specific adaptations, data imports, integrations and automations are assessed separately according to your needs."},
    es:{aboutTitle:"El estudio — KageCrest Studio",heroTitle:"El CRM inteligente, con instalación autónoma o asistida.",turnkey:"Instalación flexible",processKicker:"Dos modos de instalación",processTitle:"Instale Genable AI usted mismo o confíenos su puesta en marcha.",step1Title:"Instalación autónoma",step1Copy:"Instale y configure la solución con la documentación incluida, sin gastos adicionales de instalación.",step2Title:"Instalación asistida",step2Copy:"Podemos instalar, configurar y preparar su entorno. Este servicio opcional se añade al presupuesto.",step3Title:"Configuración profesional",step3Copy:"Las adaptaciones, importaciones de datos, integraciones y automatizaciones específicas se evalúan por separado según sus necesidades."},
    it:{aboutTitle:"Lo studio — KageCrest Studio",heroTitle:"Il CRM intelligente, da installare in autonomia o con assistenza.",turnkey:"Installazione flessibile",processKicker:"Due modalità di installazione",processTitle:"Installa Genable AI in autonomia oppure affidaci la configurazione.",step1Title:"Installazione autonoma",step1Copy:"Installa e configura la soluzione con la documentazione fornita, senza costi di installazione aggiuntivi.",step2Title:"Installazione assistita",step2Copy:"Possiamo installare, configurare e preparare il tuo ambiente. Questo servizio opzionale viene aggiunto al preventivo.",step3Title:"Configurazione professionale",step3Copy:"Adattamenti, importazioni dati, integrazioni e automazioni specifiche vengono valutati separatamente in base alle esigenze."},
    de:{aboutTitle:"Das Studio — KageCrest Studio",heroTitle:"Das intelligente CRM – selbst installieren oder begleiten lassen.",turnkey:"Flexible Installation",processKicker:"Zwei Installationsmöglichkeiten",processTitle:"Installieren Sie Genable AI selbst oder lassen Sie es von uns einrichten.",step1Title:"Eigenständige Installation",step1Copy:"Installieren und konfigurieren Sie die Lösung mithilfe der Dokumentation ohne zusätzliche Installationskosten.",step2Title:"Begleitete Installation",step2Copy:"Wir können Ihre Umgebung installieren, konfigurieren und vorbereiten. Diese optionale Leistung wird dem Angebot hinzugefügt.",step3Title:"Branchenspezifische Konfiguration",step3Copy:"Spezielle Anpassungen, Datenimporte, Integrationen und Automatisierungen werden je nach Bedarf separat bewertet."},
    zh:{aboutTitle:"工作室 — KageCrest Studio",heroTitle:"智能 CRM，可自行安装或选择协助。",turnkey:"灵活安装",processKicker:"两种安装方式",processTitle:"自行安装 Genable AI，或委托我们完成部署。",step1Title:"自行安装",step1Copy:"使用随附文档自行安装和配置，无需支付额外安装费用。",step2Title:"协助安装",step2Copy:"我们可以安装、配置并准备您的环境。此项可选服务将加入报价。",step3Title:"业务配置",step3Copy:"特定适配、数据导入、系统集成和自动化将根据需求单独评估。"},
    ja:{aboutTitle:"スタジオ — KageCrest Studio",heroTitle:"自分で導入するか、サポートを選べるインテリジェントCRM。",turnkey:"柔軟な導入方法",processKicker:"二つの導入方法",processTitle:"Genable AIを自分で導入するか、私たちにセットアップを依頼できます。",step1Title:"セルフインストール",step1Copy:"付属ドキュメントを使って自分で導入・設定でき、追加の導入費用はかかりません。",step2Title:"導入サポート",step2Copy:"環境の導入、設定、準備を代行できます。このオプションサービスは見積もりに追加されます。",step3Title:"業務向け設定",step3Copy:"個別調整、データ移行、外部連携、自動化は要件に応じて別途評価します。"},
    ko:{aboutTitle:"스튜디오 — KageCrest Studio",heroTitle:"직접 설치하거나 지원을 선택할 수 있는 지능형 CRM.",turnkey:"유연한 설치",processKicker:"두 가지 설치 방식",processTitle:"Genable AI를 직접 설치하거나 설정을 맡길 수 있습니다.",step1Title:"직접 설치",step1Copy:"제공되는 문서를 이용해 직접 설치하고 구성할 수 있으며 추가 설치 비용은 없습니다.",step2Title:"설치 지원",step2Copy:"환경 설치, 구성과 준비를 지원할 수 있습니다. 이 선택 서비스는 견적에 추가됩니다.",step3Title:"업무 맞춤 구성",step3Copy:"특정 맞춤 설정, 데이터 가져오기, 연동과 자동화는 요구사항에 따라 별도로 평가됩니다."}
  };
  Object.entries(pageRefresh).forEach(([lang, copy]) => {
    if (D[lang]?.about) D[lang].about.title = copy.aboutTitle;
    if (D[lang]?.genable) Object.assign(D[lang].genable, copy);
  });

  Object.keys(D).forEach(lang => {
    const g = D[lang].genable;
    if (g) {
      Object.keys(g).forEach(key => { if (typeof g[key] === "string") g[key] = g[key].replaceAll("Genable AI (WIP)", "Genable AI"); });
    }
    const r = D[lang].roadmap;
    if (r?.timelineIntro && lang === "fr") r.timelineIntro = "La feuille de route distingue notre activité principale de jeux vidéo et notre pôle secondaire de produits numériques.";
  });
})();
