window.FEATHER_TRANSLATIONS = window.FEATHER_TRANSLATIONS || {};
Object.assign(window.FEATHER_TRANSLATIONS, {
  en: {
    languageLabel:'Language', title:'Feather Labs Interactive — Pipi Panic', description:'Feather Labs Interactive — independent studio. Discover Pipi Panic, a mobile game developed with Flutter and Flame.',
    navGame:'Pipi Panic', navAuthors:'Authors', navSocial:'Social', heroTitle:'Chaos begins when urgency can no longer wait.', discover:'Discover the game', authors:'The authors', technologies:'Technologies',
    gameKicker:'Mobile game', gameIntro:'An offbeat mobile experience designed for immediate sessions, a confident cartoon identity, and situations that are as absurd as they are urgent.', gameTitle:'Pipi Panic', gameHeading:'A mobile game under pressure.', gameText:'An experience built for phones, with a bold cartoon identity, absurd situations, and a direct approach to mobile gaming.', platform:'Platform', engine:'Engine', studio:'Studio', status:'Status',
    authorsKicker:'Co-authors', authorsTitle:'Two creators behind Feather Labs Interactive.', authorsText:'Follow the project’s authors on their official channels. Instagram, X, TikTok, and other platform links will be added once their official URLs are confirmed.', coauthor:'Co-author', ikarugaText:'Founder of Feather Labs Interactive and co-author of Pipi Panic.', condorText:'Co-author of Pipi Panic and member of Feather Labs Interactive.', privacy:'Privacy Policy', terms:'Terms of Use', homeAria:'Feather Labs Interactive — home', legalAria:'Legal information',
    legal:{home:'Home',privacy:'Privacy',terms:'Terms',contact:'Contact',kicker:'Pipi Panic · Legal',privacyTitle:'Privacy Policy',privacyLead:'How Pipi Panic and its third-party services may process personal data.',termsTitle:'Terms of Use',termsLead:'The terms that govern installation and use of the Pipi Panic mobile application.',effective:'Effective date: 26 June 2026',scopeLabel:'Scope.',scopeText:'This document applies to the Pipi Panic mobile application and related services operated by Feather Labs. It is written for the current version of the Application and will be updated when the Application’s data practices or features materially change.',onThisPage:'On this page',footerAria:'Footer navigation'}
  },
  fr: {
    languageLabel:'Langue', title:'Feather Labs Interactive — Pipi Panic', description:'Feather Labs Interactive — studio indépendant. Découvrez Pipi Panic, un jeu mobile développé avec Flutter et Flame.',
    navGame:'Pipi Panic', navAuthors:'Auteurs', navSocial:'Réseaux', heroTitle:'Le chaos commence quand l’urgence ne peut plus attendre.', discover:'Découvrir le jeu', authors:'Les auteurs', technologies:'Technologies',
    gameKicker:'Jeu mobile', gameIntro:'Une expérience mobile décalée, pensée pour des parties directes, une identité cartoon assumée et des situations aussi absurdes qu’urgentes.', gameTitle:'Pipi Panic', gameHeading:'Un jeu mobile sous pression.', gameText:'Une expérience construite pour le téléphone, avec une identité cartoon assumée, des situations absurdes et une approche directe du jeu mobile.', platform:'Plateforme', engine:'Moteur', studio:'Studio', status:'État',
    authorsKicker:'Co-auteurs', authorsTitle:'Deux créateurs derrière Feather Labs Interactive.', authorsText:'Suivez les auteurs du projet sur leurs chaînes officielles. Les liens Instagram, X, TikTok et les autres plateformes seront ajoutés dès que leurs URL officielles seront définies.', coauthor:'Co-auteur', ikarugaText:'Créateur de Feather Labs Interactive et co-auteur de Pipi Panic.', condorText:'Co-auteur de Pipi Panic et membre de Feather Labs Interactive.', privacy:'Politique de confidentialité', terms:'Conditions d’utilisation', homeAria:'Feather Labs Interactive — accueil', legalAria:'Informations légales',
    legal:{home:'Accueil',privacy:'Confidentialité',terms:'Conditions',contact:'Contact',kicker:'Pipi Panic · Informations légales',privacyTitle:'Politique de confidentialité',privacyLead:'Comment Pipi Panic et ses services tiers peuvent traiter des données personnelles.',termsTitle:'Conditions d’utilisation',termsLead:'Les conditions qui régissent l’installation et l’utilisation de l’application mobile Pipi Panic.',effective:'Date d’effet : 26 juin 2026',scopeLabel:'Champ d’application.',scopeText:'Ce document s’applique à l’application mobile Pipi Panic et aux services associés exploités par Feather Labs. Il décrit la version actuelle de l’Application et sera mis à jour lorsque ses pratiques de données ou ses fonctionnalités évolueront de manière importante.',onThisPage:'Sur cette page',footerAria:'Navigation de pied de page'}
  },
  es: {
    languageLabel:'Idioma', title:'Feather Labs Interactive — Pipi Panic', description:'Feather Labs Interactive — estudio independiente. Descubre Pipi Panic, un juego móvil desarrollado con Flutter y Flame.',
    navGame:'Pipi Panic', navAuthors:'Autores', navSocial:'Redes', heroTitle:'El caos comienza cuando la urgencia ya no puede esperar.', discover:'Descubrir el juego', authors:'Los autores', technologies:'Tecnologías',
    gameKicker:'Juego móvil', gameIntro:'Una experiencia móvil desenfadada, pensada para partidas directas, con una identidad cartoon marcada y situaciones tan absurdas como urgentes.', gameTitle:'Pipi Panic', gameHeading:'Un juego móvil bajo presión.', gameText:'Una experiencia creada para el teléfono, con una identidad cartoon asumida, situaciones absurdas y un enfoque directo del juego móvil.', platform:'Plataforma', engine:'Motor', studio:'Estudio', status:'Estado',
    authorsKicker:'Coautores', authorsTitle:'Dos creadores detrás de Feather Labs Interactive.', authorsText:'Sigue a los autores del proyecto en sus canales oficiales. Los enlaces de Instagram, X, TikTok y otras plataformas se añadirán cuando sus URL oficiales estén confirmadas.', coauthor:'Coautor', ikarugaText:'Creador de Feather Labs Interactive y coautor de Pipi Panic.', condorText:'Coautor de Pipi Panic y miembro de Feather Labs Interactive.', privacy:'Política de privacidad', terms:'Términos de uso', homeAria:'Feather Labs Interactive — inicio', legalAria:'Información legal',
    legal:{home:'Inicio',privacy:'Privacidad',terms:'Términos',contact:'Contacto',kicker:'Pipi Panic · Información legal',privacyTitle:'Política de privacidad',privacyLead:'Cómo Pipi Panic y sus servicios de terceros pueden tratar datos personales.',termsTitle:'Términos de uso',termsLead:'Las condiciones que regulan la instalación y el uso de la aplicación móvil Pipi Panic.',effective:'Fecha de entrada en vigor: 26 de junio de 2026',scopeLabel:'Alcance.',scopeText:'Este documento se aplica a la aplicación móvil Pipi Panic y a los servicios relacionados operados por Feather Labs. Se ha redactado para la versión actual de la Aplicación y se actualizará cuando cambien de forma relevante sus prácticas de datos o funcionalidades.',onThisPage:'En esta página',footerAria:'Navegación del pie de página'}
  },
  it: {
    languageLabel:'Lingua', title:'Feather Labs Interactive — Pipi Panic', description:'Feather Labs Interactive — studio indipendente. Scopri Pipi Panic, un gioco mobile sviluppato con Flutter e Flame.',
    navGame:'Pipi Panic', navAuthors:'Autori', navSocial:'Social', heroTitle:'Il caos comincia quando l’urgenza non può più aspettare.', discover:'Scopri il gioco', authors:'Gli autori', technologies:'Tecnologie',
    gameKicker:'Gioco mobile', gameIntro:'Un’esperienza mobile fuori dagli schemi, pensata per sessioni immediate, con un’identità cartoon decisa e situazioni tanto assurde quanto urgenti.', gameTitle:'Pipi Panic', gameHeading:'Un gioco mobile sotto pressione.', gameText:'Un’esperienza costruita per il telefono, con un’identità cartoon decisa, situazioni assurde e un approccio diretto al gioco mobile.', platform:'Piattaforma', engine:'Motore', studio:'Studio', status:'Stato',
    authorsKicker:'Coautori', authorsTitle:'Due creatori dietro Feather Labs Interactive.', authorsText:'Segui gli autori del progetto sui loro canali ufficiali. I collegamenti a Instagram, X, TikTok e alle altre piattaforme saranno aggiunti quando saranno definite le rispettive URL ufficiali.', coauthor:'Coautore', ikarugaText:'Creatore di Feather Labs Interactive e coautore di Pipi Panic.', condorText:'Coautore di Pipi Panic e membro di Feather Labs Interactive.', privacy:'Informativa sulla privacy', terms:'Termini di utilizzo', homeAria:'Feather Labs Interactive — home', legalAria:'Informazioni legali',
    legal:{home:'Home',privacy:'Privacy',terms:'Termini',contact:'Contatto',kicker:'Pipi Panic · Informazioni legali',privacyTitle:'Informativa sulla privacy',privacyLead:'Come Pipi Panic e i suoi servizi di terze parti possono trattare i dati personali.',termsTitle:'Termini di utilizzo',termsLead:'I termini che disciplinano l’installazione e l’uso dell’applicazione mobile Pipi Panic.',effective:'Data di efficacia: 26 giugno 2026',scopeLabel:'Ambito.',scopeText:'Questo documento si applica all’applicazione mobile Pipi Panic e ai servizi correlati gestiti da Feather Labs. È redatto per la versione attuale dell’Applicazione e sarà aggiornato quando cambieranno in modo sostanziale le pratiche relative ai dati o le funzionalità.',onThisPage:'In questa pagina',footerAria:'Navigazione nel piè di pagina'}
  },
  de: {
    languageLabel:'Sprache', title:'Feather Labs Interactive — Pipi Panic', description:'Feather Labs Interactive — unabhängiges Studio. Entdecke Pipi Panic, ein mit Flutter und Flame entwickeltes Mobile-Spiel.',
    navGame:'Pipi Panic', navAuthors:'Autoren', navSocial:'Netzwerke', heroTitle:'Das Chaos beginnt, wenn die Dringlichkeit nicht länger warten kann.', discover:'Spiel entdecken', authors:'Die Autoren', technologies:'Technologien',
    gameKicker:'Mobile-Spiel', gameIntro:'Ein ungewöhnliches Mobile-Erlebnis für direkte Spielrunden, mit selbstbewusster Cartoon-Identität und Situationen, die ebenso absurd wie dringend sind.', gameTitle:'Pipi Panic', gameHeading:'Ein Mobile-Spiel unter Druck.', gameText:'Ein für Smartphones entwickeltes Erlebnis mit ausgeprägter Cartoon-Identität, absurden Situationen und einem direkten Ansatz für Mobile-Gaming.', platform:'Plattform', engine:'Engine', studio:'Studio', status:'Status',
    authorsKicker:'Co-Autoren', authorsTitle:'Zwei Kreative hinter Feather Labs Interactive.', authorsText:'Folge den Autoren des Projekts auf ihren offiziellen Kanälen. Links zu Instagram, X, TikTok und weiteren Plattformen werden ergänzt, sobald die offiziellen URLs feststehen.', coauthor:'Co-Autor', ikarugaText:'Gründer von Feather Labs Interactive und Co-Autor von Pipi Panic.', condorText:'Co-Autor von Pipi Panic und Mitglied von Feather Labs Interactive.', privacy:'Datenschutzerklärung', terms:'Nutzungsbedingungen', homeAria:'Feather Labs Interactive — Startseite', legalAria:'Rechtliche Informationen',
    legal:{home:'Startseite',privacy:'Datenschutz',terms:'Bedingungen',contact:'Kontakt',kicker:'Pipi Panic · Rechtliche Informationen',privacyTitle:'Datenschutzerklärung',privacyLead:'Wie Pipi Panic und seine Drittanbieterdienste personenbezogene Daten verarbeiten können.',termsTitle:'Nutzungsbedingungen',termsLead:'Die Bedingungen für Installation und Nutzung der mobilen Anwendung Pipi Panic.',effective:'Gültig ab: 26. Juni 2026',scopeLabel:'Geltungsbereich.',scopeText:'Dieses Dokument gilt für die mobile Anwendung Pipi Panic und die damit verbundenen Dienste von Feather Labs. Es bezieht sich auf die aktuelle Version der Anwendung und wird aktualisiert, wenn sich Datenpraktiken oder Funktionen wesentlich ändern.',onThisPage:'Auf dieser Seite',footerAria:'Fußzeilennavigation'}
  },
  zh: {
    languageLabel:'语言', title:'Feather Labs Interactive — Pipi Panic', description:'Feather Labs Interactive — 独立工作室。探索使用 Flutter 和 Flame 开发的移动游戏 Pipi Panic。',
    navGame:'Pipi Panic', navAuthors:'作者', navSocial:'社交媒体', heroTitle:'当紧急情况再也无法等待，混乱便开始了。', discover:'发现游戏', authors:'作者介绍', technologies:'技术',
    gameKicker:'手机游戏', gameIntro:'一款风格独特的移动游戏体验，面向即时游玩，拥有鲜明的卡通风格和既荒诞又紧急的情境。', gameTitle:'Pipi Panic', gameHeading:'压力之下的手机游戏。', gameText:'专为手机打造的体验，具备鲜明的卡通风格、荒诞的情境，以及直接易玩的移动游戏方式。', platform:'平台', engine:'引擎', studio:'工作室', status:'状态',
    authorsKicker:'联合作者', authorsTitle:'Feather Labs Interactive 背后的两位创作者。', authorsText:'请在官方频道关注本项目的作者。Instagram、X、TikTok 及其他平台链接将在其官方网址确定后添加。', coauthor:'联合作者', ikarugaText:'Feather Labs Interactive 的创建者，也是 Pipi Panic 的联合作者。', condorText:'Pipi Panic 的联合作者，也是 Feather Labs Interactive 的成员。', privacy:'隐私政策', terms:'使用条款', homeAria:'Feather Labs Interactive — 首页', legalAria:'法律信息',
    legal:{home:'首页',privacy:'隐私',terms:'条款',contact:'联系',kicker:'Pipi Panic · 法律信息',privacyTitle:'隐私政策',privacyLead:'Pipi Panic 及其第三方服务如何处理个人数据。',termsTitle:'使用条款',termsLead:'适用于安装和使用 Pipi Panic 移动应用程序的条款。',effective:'生效日期：2026 年 6 月 26 日',scopeLabel:'适用范围。',scopeText:'本文件适用于 Pipi Panic 移动应用程序以及 Feather Labs 运营的相关服务。其依据是应用程序的当前版本；当数据处理实践或功能发生重大变化时，将会更新。',onThisPage:'本页内容',footerAria:'页脚导航'}
  },
  ja: {
    languageLabel:'言語', title:'Feather Labs Interactive — Pipi Panic', description:'Feather Labs Interactive — インディペンデントスタジオ。Flutter と Flame で開発されたモバイルゲーム、Pipi Panic を紹介します。',
    navGame:'Pipi Panic', navAuthors:'制作者', navSocial:'SNS', heroTitle:'待ったなしの緊急事態から、カオスが始まる。', discover:'ゲームを見る', authors:'制作者について', technologies:'技術',
    gameKicker:'モバイルゲーム', gameIntro:'すぐに遊べることを重視し、強いカートゥーン性と、ばかばかしくも切迫した状況を備えた一風変わったモバイル体験です。', gameTitle:'Pipi Panic', gameHeading:'プレッシャー下のモバイルゲーム。', gameText:'スマートフォンのために作られた、明確なカートゥーン性、ばかばかしい状況、そして直接的なゲーム体験を備えた作品です。', platform:'プラットフォーム', engine:'エンジン', studio:'スタジオ', status:'ステータス',
    authorsKicker:'共同制作者', authorsTitle:'Feather Labs Interactive を支える二人のクリエイター。', authorsText:'プロジェクトの制作者を公式チャンネルでフォローしてください。Instagram、X、TikTok などへのリンクは、公式 URL が確定次第追加されます。', coauthor:'共同制作者', ikarugaText:'Feather Labs Interactive の創設者であり、Pipi Panic の共同制作者。', condorText:'Pipi Panic の共同制作者であり、Feather Labs Interactive のメンバー。', privacy:'プライバシーポリシー', terms:'利用規約', homeAria:'Feather Labs Interactive — ホーム', legalAria:'法的情報',
    legal:{home:'ホーム',privacy:'プライバシー',terms:'規約',contact:'お問い合わせ',kicker:'Pipi Panic · 法的情報',privacyTitle:'プライバシーポリシー',privacyLead:'Pipi Panic および第三者サービスによる個人データの取扱いについて。',termsTitle:'利用規約',termsLead:'Pipi Panic モバイルアプリのインストールおよび利用に適用される規約。',effective:'発効日：2026年6月26日',scopeLabel:'適用範囲。',scopeText:'本書は、Pipi Panic モバイルアプリケーションおよび Feather Labs が運営する関連サービスに適用されます。現在のアプリケーションを対象とし、データ取扱いまたは機能に重要な変更がある場合に更新されます。',onThisPage:'このページの内容',footerAria:'フッターナビゲーション'}
  },
  ko: {
    languageLabel:'언어', title:'Feather Labs Interactive — Pipi Panic', description:'Feather Labs Interactive — 독립 스튜디오. Flutter와 Flame으로 개발한 모바일 게임 Pipi Panic을 만나 보세요.',
    navGame:'Pipi Panic', navAuthors:'제작자', navSocial:'소셜', heroTitle:'더는 기다릴 수 없는 긴급함 속에서 혼돈이 시작됩니다.', discover:'게임 알아보기', authors:'제작자 소개', technologies:'기술',
    gameKicker:'모바일 게임', gameIntro:'즉시 플레이할 수 있도록 설계한 색다른 모바일 경험입니다. 뚜렷한 카툰 감성과 터무니없지만 긴박한 상황을 담았습니다.', gameTitle:'Pipi Panic', gameHeading:'압박 속의 모바일 게임.', gameText:'휴대폰을 위해 만든 경험으로, 선명한 카툰 정체성, 황당한 상황, 직관적인 모바일 게임 방식을 갖추고 있습니다.', platform:'플랫폼', engine:'엔진', studio:'스튜디오', status:'상태',
    authorsKicker:'공동 제작자', authorsTitle:'Feather Labs Interactive를 이끄는 두 명의 크리에이터.', authorsText:'프로젝트 제작자를 공식 채널에서 팔로우하세요. Instagram, X, TikTok 및 기타 플랫폼 링크는 공식 URL이 확정되는 대로 추가됩니다.', coauthor:'공동 제작자', ikarugaText:'Feather Labs Interactive의 설립자이자 Pipi Panic의 공동 제작자입니다.', condorText:'Pipi Panic의 공동 제작자이자 Feather Labs Interactive의 구성원입니다.', privacy:'개인정보 처리방침', terms:'이용 약관', homeAria:'Feather Labs Interactive — 홈', legalAria:'법률 정보',
    legal:{home:'홈',privacy:'개인정보',terms:'약관',contact:'문의',kicker:'Pipi Panic · 법률 정보',privacyTitle:'개인정보 처리방침',privacyLead:'Pipi Panic 및 제3자 서비스가 개인 데이터를 처리할 수 있는 방식입니다.',termsTitle:'이용 약관',termsLead:'Pipi Panic 모바일 애플리케이션의 설치 및 사용에 적용되는 약관입니다.',effective:'시행일: 2026년 6월 26일',scopeLabel:'적용 범위.',scopeText:'이 문서는 Pipi Panic 모바일 애플리케이션과 Feather Labs가 운영하는 관련 서비스에 적용됩니다. 현재 버전의 애플리케이션을 기준으로 작성되었으며, 데이터 처리 관행 또는 기능이 중대하게 변경되면 업데이트됩니다.',onThisPage:'이 페이지의 내용',footerAria:'바닥글 탐색'}
  }
});
